name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚧 Breaking changes"
    labels:
      - "major-bump"
  - title: "🚀 New Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "other"
      - "dependencies"
  - title: "📝 Documentation"
    labels:
      - "documentation"
version-resolver:
  major:
    labels:
      - "major-bump"
  minor:
    labels:
      - "minor-bump"
      - "feature"
  patch:
    labels:
      - "patch-bump"
  default: patch
exclude-labels:
  - "skip-changelog"
autolabeler:
  - label: "chore"
    title:
      - "/chore/i"
    branch:
      - '/chore\/.+/'
      - '/dependabot\/.+/'
  - label: "fix"
    title:
      - "/fix/i"
    branch:
      - '/fix\/.+/'
  - label: "feature"
    title:
      - "/feat/i"
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
  - label: "documentation"
    title:
      - "/docs/i"
    branch:
      - '/docs\/.+/'
template: |
  # Changes since $PREVIOUS_TAG

  $CHANGES
