linters:
  enable:
    - "asciicheck"
    - "bodyclose"
    - "cyclop"
    - "deadcode"
    - "depguard"
    - "dogsled"
    - "errcheck"
    - "errorlint"
    - "errname"
    - "exportloopref"
    - "exhaustive"
    - "gofmt"
    - "gofumpt"
    - "goheader"
    - "goimports"
    - "gci"
    - "gochecknoglobals"
    - "gochecknoinits"
    - "goconst"
    - "godot"
    - "gomodguard"
    - "goprintffuncname"
    - "gosec"
    - "ifshort"
    - "gosimple"
    - "govet"
    - "ineffassign"
    - "makezero"
    - "misspell"
    - "nestif"
    - "nilerr"
    - "noctx"
    - "paralleltest"
    - "prealloc"
    - "predeclared"
    - "revive"
    - "sqlclosecheck"
    - "staticcheck"
    - "structcheck"
    - "stylecheck"
#    - "typecheck"
    - "unconvert"
    - "unused"
    - "varcheck"
    - "whitespace"
    - "forcetypeassert"
    - "gomoddirectives"
