version: 2
jobs:
  build-backend:
    working_directory: ~/itbio/backend
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout:
          path: ~/itbio
      - run: gradle clean build
  build-frontend:
    working_directory: ~/itbio/frontend
    docker:
      - image: circleci/node:8.1.2
    steps:
      - checkout:
          path: ~/itbio
      - run: npm install
      - run: npm run build
workflows:
  version: 2
  build:
    jobs:
      - build-backend
      - build-frontend
