services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: filmstund
      POSTGRES_DB: filmstund
      POSTGRES_PASSWORD: filmstund
