// Code generated by sqlc. DO NOT EDIT.

package dao

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Attendee struct {
	UserID              uuid.UUID      `json:"userID"`
	ShowingID           uuid.UUID      `json:"showingID"`
	AttendeeType        string         `json:"attendeeType"`
	HasPaid             bool           `json:"hasPaid"`
	AmountOwed          int32          `json:"amountOwed"`
	GiftCertificateUsed sql.NullString `json:"giftCertificateUsed"`
	UpdateTime          time.Time      `json:"updateTime"`
	CreateTime          time.Time      `json:"createTime"`
}

type CinemaScreen struct {
	ID         string         `json:"id"`
	Name       sql.NullString `json:"name"`
	CreateTime time.Time      `json:"createTime"`
}

type Commandment struct {
	Number     int32     `json:"number"`
	Phrase     string    `json:"phrase"`
	CreateTime time.Time `json:"createTime"`
}

type GiftCertificate struct {
	UserID     uuid.UUID `json:"userID"`
	Number     string    `json:"number"`
	ExpireTime time.Time `json:"expireTime"`
	CreateTime time.Time `json:"createTime"`
}

type Location struct {
	Name          string          `json:"name"`
	CityAlias     sql.NullString  `json:"cityAlias"`
	City          sql.NullString  `json:"city"`
	StreetAddress sql.NullString  `json:"streetAddress"`
	PostalCode    sql.NullString  `json:"postalCode"`
	PostalAddress sql.NullString  `json:"postalAddress"`
	Latitude      sql.NullFloat64 `json:"latitude"`
	Longitude     sql.NullFloat64 `json:"longitude"`
	FilmstadenID  sql.NullString  `json:"filmstadenID"`
	UpdateTime    time.Time       `json:"updateTime"`
	CreateTime    time.Time       `json:"createTime"`
}

type LocationAlias struct {
	Location   sql.NullString `json:"location"`
	Alias      string         `json:"alias"`
	UpdateTime time.Time      `json:"updateTime"`
	CreateTime time.Time      `json:"createTime"`
}

type Movie struct {
	ID             uuid.UUID      `json:"id"`
	FilmstadenID   string         `json:"filmstadenID"`
	ImdbID         sql.NullString `json:"imdbID"`
	TmdbID         sql.NullInt64  `json:"tmdbID"`
	Slug           string         `json:"slug"`
	Title          string         `json:"title"`
	ReleaseDate    sql.NullTime   `json:"releaseDate"`
	ProductionYear int32          `json:"productionYear"`
	Runtime        int32          `json:"runtime"`
	Poster         sql.NullString `json:"poster"`
	Genres         []string       `json:"genres"`
	Archived       bool           `json:"archived"`
	UpdateTime     time.Time      `json:"updateTime"`
	CreateTime     time.Time      `json:"createTime"`
}

type Showing struct {
	ID                  uuid.UUID      `json:"id"`
	WebID               string         `json:"webID"`
	Slug                string         `json:"slug"`
	Date                time.Time      `json:"date"`
	Time                time.Time      `json:"time"`
	MovieID             uuid.UUID      `json:"movieID"`
	LocationID          string         `json:"locationID"`
	CinemaScreenID      sql.NullString `json:"cinemaScreenID"`
	FilmstadenShowingID sql.NullString `json:"filmstadenShowingID"`
	Price               int32          `json:"price"`
	TicketsBought       bool           `json:"ticketsBought"`
	Admin               uuid.UUID      `json:"admin"`
	PayToUser           uuid.UUID      `json:"payToUser"`
	UpdateTime          time.Time      `json:"updateTime"`
	CreateTime          time.Time      `json:"createTime"`
}

type Ticket struct {
	ID                     string         `json:"id"`
	ShowingID              uuid.NullUUID  `json:"showingID"`
	AssignedToUser         uuid.NullUUID  `json:"assignedToUser"`
	ProfileID              sql.NullString `json:"profileID"`
	Barcode                string         `json:"barcode"`
	CustomerType           string         `json:"customerType"`
	CustomerTypeDefinition string         `json:"customerTypeDefinition"`
	Cinema                 string         `json:"cinema"`
	CinemaCity             sql.NullString `json:"cinemaCity"`
	Screen                 string         `json:"screen"`
	SeatRow                int32          `json:"seatRow"`
	SeatNumber             int32          `json:"seatNumber"`
	Date                   time.Time      `json:"date"`
	Time                   time.Time      `json:"time"`
	MovieName              string         `json:"movieName"`
	MovieRating            string         `json:"movieRating"`
	Attributes             []string       `json:"attributes"`
	UpdateTime             time.Time      `json:"updateTime"`
	CreateTime             time.Time      `json:"createTime"`
}

type User struct {
	ID                     uuid.UUID      `json:"id"`
	SubjectID              string         `json:"subjectID"`
	FilmstadenMembershipID sql.NullString `json:"filmstadenMembershipID"`
	FirstName              string         `json:"firstName"`
	LastName               string         `json:"lastName"`
	Nick                   sql.NullString `json:"nick"`
	Email                  string         `json:"email"`
	Phone                  sql.NullString `json:"phone"`
	Avatar                 sql.NullString `json:"avatar"`
	CalendarFeedID         uuid.NullUUID  `json:"calendarFeedID"`
	LastLoginTime          time.Time      `json:"lastLoginTime"`
	SignupTime             time.Time      `json:"signupTime"`
	UpdateTime             time.Time      `json:"updateTime"`
}
