// Code generated by sqlc. DO NOT EDIT.
// source: showings.sql

package dao

import (
	"context"

	"github.com/google/uuid"
)

const adminOnShowing = `-- name: AdminOnShowing :one
SELECT exists(SELECT 1
              FROM showings s
              WHERE s.admin = $1
                AND s.id = $2)
`

type AdminOnShowingParams struct {
	AdminUserID uuid.UUID `json:"adminUserID"`
	ShowingID   uuid.UUID `json:"showingID"`
}

func (q *Queries) AdminOnShowing(ctx context.Context, arg AdminOnShowingParams) (bool, error) {
	row := q.db.QueryRow(ctx, adminOnShowing, arg.AdminUserID, arg.ShowingID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
