// Code generated by sqlc. DO NOT EDIT.
// source: users.sql

package dao

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addGiftCertificate = `-- name: AddGiftCertificate :exec
INSERT INTO gift_certificate (user_id, number, expire_time)
values ($1, $2, $3)
`

type AddGiftCertificateParams struct {
	UserID     uuid.UUID `json:"userID"`
	Number     string    `json:"number"`
	ExpireTime time.Time `json:"expireTime"`
}

func (q *Queries) AddGiftCertificate(ctx context.Context, arg AddGiftCertificateParams) error {
	_, err := q.db.Exec(ctx, addGiftCertificate, arg.UserID, arg.Number, arg.ExpireTime)
	return err
}

const createUpdateUser = `-- name: CreateUpdateUser :one
INSERT INTO users
    (subject_id, first_name, last_name, nick, email, avatar)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (subject_id) DO UPDATE SET last_login_time = current_timestamp,
                                       email           = $5,
                                       avatar          = $6,
                                       update_time     = current_timestamp
RETURNING id
`

type CreateUpdateUserParams struct {
	Subject   string         `json:"subject"`
	FirstName string         `json:"firstName"`
	LastName  string         `json:"lastName"`
	Nick      sql.NullString `json:"nick"`
	Email     string         `json:"email"`
	Avatar    sql.NullString `json:"avatar"`
}

func (q *Queries) CreateUpdateUser(ctx context.Context, arg CreateUpdateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUpdateUser,
		arg.Subject,
		arg.FirstName,
		arg.LastName,
		arg.Nick,
		arg.Email,
		arg.Avatar,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteGiftCertificate = `-- name: DeleteGiftCertificate :exec
DELETE
FROM gift_certificate
WHERE user_id = $1
  AND number = $2
  AND expire_time = $3
`

type DeleteGiftCertificateParams struct {
	UserID     uuid.UUID `json:"userID"`
	Number     string    `json:"number"`
	ExpireTime time.Time `json:"expireTime"`
}

func (q *Queries) DeleteGiftCertificate(ctx context.Context, arg DeleteGiftCertificateParams) error {
	_, err := q.db.Exec(ctx, deleteGiftCertificate, arg.UserID, arg.Number, arg.ExpireTime)
	return err
}

const disableCalendarFeed = `-- name: DisableCalendarFeed :one
UPDATE users
SET calendar_feed_id = NULL
WHERE subject_id = $1
RETURNING id, subject_id, filmstaden_membership_id, first_name, last_name, nick, email, phone, avatar, calendar_feed_id, last_login_time, signup_time, update_time
`

func (q *Queries) DisableCalendarFeed(ctx context.Context, subjectID string) (User, error) {
	row := q.db.QueryRow(ctx, disableCalendarFeed, subjectID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.FilmstadenMembershipID,
		&i.FirstName,
		&i.LastName,
		&i.Nick,
		&i.Email,
		&i.Phone,
		&i.Avatar,
		&i.CalendarFeedID,
		&i.LastLoginTime,
		&i.SignupTime,
		&i.UpdateTime,
	)
	return i, err
}

const getGiftCertificates = `-- name: GetGiftCertificates :many
SELECT user_id, number, expire_time, create_time
FROM gift_certificate
WHERE user_id = $1
`

func (q *Queries) GetGiftCertificates(ctx context.Context, userID uuid.UUID) ([]GiftCertificate, error) {
	rows, err := q.db.Query(ctx, getGiftCertificates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GiftCertificate
	for rows.Next() {
		var i GiftCertificate
		if err := rows.Scan(
			&i.UserID,
			&i.Number,
			&i.ExpireTime,
			&i.CreateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, subject_id, filmstaden_membership_id, first_name, last_name, nick, email, phone, avatar, calendar_feed_id, last_login_time, signup_time, update_time
FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.FilmstadenMembershipID,
		&i.FirstName,
		&i.LastName,
		&i.Nick,
		&i.Email,
		&i.Phone,
		&i.Avatar,
		&i.CalendarFeedID,
		&i.LastLoginTime,
		&i.SignupTime,
		&i.UpdateTime,
	)
	return i, err
}

const listPublicUsers = `-- name: ListPublicUsers :many
SELECT id,
       (first_name || ' ' || users.last_name)::text as name,
       first_name,
       last_name,
       nick,
       phone,
       avatar                                       as avatar_url
FROM users
WHERE id = ANY($1::uuid[])
`

type ListPublicUsersRow struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	FirstName string         `json:"firstName"`
	LastName  string         `json:"lastName"`
	Nick      sql.NullString `json:"nick"`
	Phone     sql.NullString `json:"phone"`
	AvatarURL sql.NullString `json:"avatarUrl"`
}

func (q *Queries) ListPublicUsers(ctx context.Context, ids []uuid.UUID) ([]ListPublicUsersRow, error) {
	rows, err := q.db.Query(ctx, listPublicUsers, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicUsersRow
	for rows.Next() {
		var i ListPublicUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FirstName,
			&i.LastName,
			&i.Nick,
			&i.Phone,
			&i.AvatarURL,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publicUser = `-- name: PublicUser :one
SELECT id,
       (first_name || ' ' || users.last_name)::text as name,
       first_name,
       last_name,
       nick,
       phone,
       avatar                                       as avatar_url
FROM users
WHERE id = $1
`

type PublicUserRow struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	FirstName string         `json:"firstName"`
	LastName  string         `json:"lastName"`
	Nick      sql.NullString `json:"nick"`
	Phone     sql.NullString `json:"phone"`
	AvatarURL sql.NullString `json:"avatarUrl"`
}

func (q *Queries) PublicUser(ctx context.Context, id uuid.UUID) (PublicUserRow, error) {
	row := q.db.QueryRow(ctx, publicUser, id)
	var i PublicUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FirstName,
		&i.LastName,
		&i.Nick,
		&i.Phone,
		&i.AvatarURL,
	)
	return i, err
}

const randomizeCalendarFeed = `-- name: RandomizeCalendarFeed :one
UPDATE users
SET calendar_feed_id = uuid_generate_v4()
WHERE subject_id = $1
RETURNING id, subject_id, filmstaden_membership_id, first_name, last_name, nick, email, phone, avatar, calendar_feed_id, last_login_time, signup_time, update_time
`

func (q *Queries) RandomizeCalendarFeed(ctx context.Context, subjectID string) (User, error) {
	row := q.db.QueryRow(ctx, randomizeCalendarFeed, subjectID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.FilmstadenMembershipID,
		&i.FirstName,
		&i.LastName,
		&i.Nick,
		&i.Email,
		&i.Phone,
		&i.Avatar,
		&i.CalendarFeedID,
		&i.LastLoginTime,
		&i.SignupTime,
		&i.UpdateTime,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET filmstaden_membership_id = COALESCE(NULLIF(TRIM($1), ''), filmstaden_membership_id),
    phone                    = COALESCE(NULLIF(TRIM($2), ''), phone),
    first_name               = COALESCE(NULLIF(TRIM($3), ''), first_name),
    last_name                = COALESCE(NULLIF(TRIM($4), ''), last_name),
    nick                     = COALESCE(NULLIF(TRIM($5), ''), nick),
    update_time              = current_timestamp
WHERE subject_id = $6
RETURNING id, subject_id, filmstaden_membership_id, first_name, last_name, nick, email, phone, avatar, calendar_feed_id, last_login_time, signup_time, update_time
`

type UpdateUserParams struct {
	FilmstadenMembershipID string `json:"filmstadenMembershipID"`
	PhoneNumber            string `json:"phoneNumber"`
	FirstName              string `json:"firstName"`
	LastName               string `json:"lastName"`
	Nick                   string `json:"nick"`
	SubjectID              string `json:"subjectID"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FilmstadenMembershipID,
		arg.PhoneNumber,
		arg.FirstName,
		arg.LastName,
		arg.Nick,
		arg.SubjectID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.FilmstadenMembershipID,
		&i.FirstName,
		&i.LastName,
		&i.Nick,
		&i.Email,
		&i.Phone,
		&i.Avatar,
		&i.CalendarFeedID,
		&i.LastLoginTime,
		&i.SignupTime,
		&i.UpdateTime,
	)
	return i, err
}

const userExistsBySubject = `-- name: UserExistsBySubject :one
SELECT exists(SELECT 1 FROM users where subject_id = $1)
`

func (q *Queries) UserExistsBySubject(ctx context.Context, subjectID string) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsBySubject, subjectID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
