version: 2.1

orbs:
  packtracker: packtracker/report@2.2.2

defaults: &defaults
  working_directory: ~/itbio

jobs:
  test-backend:
    <<: *defaults
    docker:
      - image: circleci/openjdk:11-browsers-legacy
    steps:
      - checkout
      - restore_cache:
          key: gradle-{{ checksum "backend/build.gradle" }}
      - run: |
          cd backend
          ./gradlew check
      - save_cache:
          key: gradle-{{ checksum "backend/build.gradle" }}
          paths:
            - ~/.gradle
  test-frontend:
    <<: *defaults
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          name: Restoring node_modules
          key: v1-node_modules-{{ checksum "frontend/yarn.lock" }}
      - run: |
          cd frontend
          yarn --pure-lockfile
      - save_cache:
          name: Caching node_modules
          key: v1-node_modules-{{ checksum "frontend/yarn.lock" }}
          paths:
            - frontend/node_modules
      - run: |
          cd frontend
          yarn test
  build-docker:
    <<: *defaults
    machine: true
    steps:
      - checkout
      - run: |
          make docker
          mkdir docker-cache
          docker save -o docker-cache/images.tar cthdidit/sefilm-frontend cthdidit/sefilm-backend
      - persist_to_workspace:
          root: ~/itbio
          paths:
            - docker-cache/*
  push-docker:
    <<: *defaults
    machine: true
    steps:
      - attach_workspace:
          at: ~/itbio
      - run: |
          docker load -i docker-cache/images.tar
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push cthdidit/sefilm-frontend
          docker push cthdidit/sefilm-backend

workflows:
  version: 2
  packtracker:
    jobs:
      - packtracker/report:
          project_root: "./frontend"
          webpack_config: "react-scripts/config/webpack.config"
  build:
    jobs:
      - test-backend
      - test-frontend
      - build-docker:
          requires:
            - test-frontend
            - test-backend
      - push-docker:
          requires:
            - build-docker
          filters:
            branches:
              only:
                - master
