CREATE TABLE USERS (
  ID UUID PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  NICK VARCHAR(255) NULL,
  EMAIL VARCHAR(255) UNIQUE NOT NULL,
  BIOKLUBBNUMMER VARCHAR(11) UNIQUE NOT NULL,
  PHONE VARCHAR(20) NULL
);

CREATE TABLE MOVIE (
  ID UUID PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  RUNTIME BIGINT NOT NULL, -- In nanoseconds
  IMDB VARCHAR(9) NULL UNIQUE
);

CREATE TABLE LOCATION (
  ID UUID PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  latitude FLOAT NOT NULL,
  longitude FLOAT NOT NULL
);

CREATE TABLE SHOWING (
  ID UUID PRIMARY KEY,
  START_TIME TIMESTAMP WITHOUT TIME ZONE,
  MOVIE_ID UUID REFERENCES MOVIE(ID),
  LOCATION_ID UUID REFERENCES LOCATION(ID),
  ADMIN_ID UUID REFERENCES USERS(id)
);

INSERT INTO LOCATION (ID, name, latitude, longitude) VALUES (uuid_generate_v4(), 'Filmstaden Bergakungen', 57.7022927, 11.9841099);
INSERT INTO LOCATION (ID, name, latitude, longitude) VALUES (uuid_generate_v4(), 'Biopalatset', 57.7034996, 11.9647064);

INSERT INTO USERS (ID, NAME, NICK, EMAIL, BIOKLUBBNUMMER, PHONE) VALUES (uuid_generate_v4(), 'Test admin user', 'AddyAdmin', 'apa@example.org', '11111111111', '070-000 00 00');

INSERT INTO MOVIE (ID, NAME, RUNTIME, IMDB) VALUES (uuid_generate_v4(), 'John Wick: Chapter 2', 7320000000000, 'tt4425200');

INSERT INTO SHOWING (id, start_time, movie_id, location_id, admin_id) VALUES (uuid_generate_v4(), '2017-03-26 19:08:59.042000', (SELECT id FROM MOVIE WHERE NAME='John Wick: Chapter 2'), (SELECT id FROM LOCATION WHERE name='Filmstaden Bergakungen'), (SELECT id FROM USERS WHERE NICK='AddyAdmin'));
