// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package sqlc

import (
	"context"
)

const listBioBudord = `-- name: ListBioBudord :many
SELECT number, phrase
FROM bio_budord
ORDER BY number
`

type ListBioBudordRow struct {
	Number int32  `json:"number"`
	Phrase string `json:"phrase"`
}

func (q *Queries) ListBioBudord(ctx context.Context) ([]ListBioBudordRow, error) {
	rows, err := q.db.Query(ctx, listBioBudord)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBioBudordRow
	for rows.Next() {
		var i ListBioBudordRow
		if err := rows.Scan(&i.Number, &i.Phrase); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
