server:
  port: ${SERVER_PORT:8080}

spring:
  output:
    ansi:
      enabled: ALWAYS
  data:
    mongodb:
      uri: ${SEFILM_MONGODB_URI:mongodb://localhost/sefilm}
      enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
  cache:
    cache-names: filmstadenDates,filmstadenSeatMap
    caffeine:
      spec: maximumSize=500,expireAfterWrite=43200s

management:
  endpoints:
    web:
      base-path: "/"
  info:
    git:
      mode: "full"

sefilm:
  baseUrl:
    api: ${apiBaseUrl:http://localhost:8080}
    frontend: ${frontendBaseUrl:http://localhost:3000}
  tmdb:
    # Request API key here: https://www.themoviedb.org/documentation/api
    apikey: ${tmdb_apikey}
  google:
    clientId: 692064172675-montab9pi57304e68r932c6lm7111oaf.apps.googleusercontent.com
    jwkUri: https://www.googleapis.com/oauth2/v3/certs

  # Whetever or not tickets should be auto assigned to other than admin
  enableReassignment: ${enableReassignment:true}

  # Whether or not data should be seeded on application startup
  enableSeeding: ${enableSeeding:true}
  defaultCity: ${defaultCity:GB}
  schedulers:
    enabled:
      movieUpdater: ${movieUpdaterEnabled:true}
      archiver: ${archiverEnabled:true}
      popularityUpdater: ${popularityUpdaterEnabled:true}
  notification:
    provider:
      MailProvider:
        enabled: ${mailProviderEnabled:true}
      Pushover:
        enabled: ${pushoverProviderEnabled:true}
        apiToken: ${pushoverApiToken}
        url: ${pushoverUrl:https://api.pushover.net/1/messages.json}
        validateUrl: ${pushoverValidateUrl:https://api.pushover.net/1/users/validate.json}


graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: false

logging:
  level:
    rocks.didit: ${logLevel:INFO}
