version: 1
packages:
  - path: "../../../internal/database/dao"
    name: "dao"
    engine: "postgresql"
    sql_package: "pgx/v4"
    emit_json_tags: true
    schema: "../migrations"
    queries: "../queries"
    json_tags_case_style: "camel"
    output_db_file_name: "queries.go"
