name: Backend
on:
  push:
    branches:
      - master
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  make:
    runs-on: self-hosted # runner label defined in repo settings
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17"
      - name: Build application
        run: make build
