name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  checks:
    runs-on: self-hosted # runner label defined in repo settings
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "^1.17"
      - name: Checks
        run: make checks

  build-backend:
    runs-on: self-hosted # runner label defined in repo settings
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "^1.17"
      - name: Build application
        run: make build

  build-frontend:
    runs-on: self-hosted # runner label defined in repo settings
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "yarn"
          cache-dependency-path: "web/yarn.lock"
      - name: Build frontend
        run: |
          cd web
          make all-web
        env:
          CI: true
          CI_REPO_OWNER: Filmstund
          CI_REPO_NAME: filmstund
          CI_COMMIT_SHA: ${{ github.sha }}
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
