name: Deploy beta backend

on:
  workflow_run:
    workflows: [ "Backend" ]
    branches: [ master ]
    types:
      - completed

jobs:
  deploy-backend:
    environment: preprod
    runs-on: self-hosted # runner label defined in repo settings
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17"
      - name: Build assets
        run: make build
      - name: Transfer assets to server
        env:
          USER_BACKEND: ${{ secrets.USER_BACKEND }}
          HOST_BACKEND: ${{ secrets.HOST_BACKEND }}
        run: |
          ssh $USER_BACKEND@$HOST_BACKEND mkdir --parents backend-new
          scp .build/* $USER_BACKEND@$HOST_BACKEND:backend-new/
      - name: Replace backend
        env:
          USER_BACKEND: ${{ secrets.USER_BACKEND }}
          HOST_BACKEND: ${{ secrets.HOST_BACKEND }}
        run: |
          ssh $USER_BACKEND@$HOST_BACKEND systemctl --user stop filmstund.service
          ssh $USER_BACKEND@$HOST_BACKEND systemctl --user stop popularity.service
          ssh $USER_BACKEND@$HOST_BACKEND mkdir --parents backend-old
          ssh $USER_BACKEND@$HOST_BACKEND mv backend/* backend-old/
          ssh $USER_BACKEND@$HOST_BACKEND mv backend-new/* backend/
          ssh $USER_BACKEND@$HOST_BACKEND systemctl --user start filmstund.service
          ssh $USER_BACKEND@$HOST_BACKEND systemctl --user start popularity.service
