name: deploy beta

on:
  workflow_run:
    workflows: [ "Backend" ]
    branches: [ master ]
    types:
      - completed

jobs:
  deploy-packages:
    environment: preprod
    runs-on: self-hosted # runner label defined in repo settings
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17"
      - name: Build assets
        run: make build
      - name: Transfer assets to server
        env:
          USER_BACKEND: ${{ secrets.USER_BACKEND }}
          HOST_BACKEND: ${{ secrets.HOST_BACKEND }}
        run: |
          scp .build/* $USER_BACKEND@$HOST_BACKEND:backend/
      - name: Restart backend
        run: |
          ssh $USER_BACKEND@$HOST_BACKEND systemctl --user restart filmstund.service
          ssh $USER_BACKEND@$HOST_BACKEND systemctl --user restart popularity.service
