name: deploy beta frontend

on:
  workflow_run:
    workflows: [ "Frontend" ]
    branches: [ master ]
    types:
      - completed

jobs:
  deploy-frontend:
    environment: preprod
    runs-on: self-hosted # runner label defined in repo settings
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "yarn"
          cache-dependency-path: "web/yarn.lock"
      - name: Build assets
        run: |
          cd ./web
          yarn
          yarn build
          tar cf frontend.tar.gz -C build/ .
      - name: Transfer assets to server
        env:
          USER_FRONTEND: ${{ secrets.USER_FRONTEND }}
          HOST_FRONTEND: ${{ secrets.HOST_FRONTEND }}
        run: |
          scp ./web/frontend.tar.gz $USER_FRONTEND@$HOST_FRONTEND:frontend/beta.tar.gz
      - name: Replace frontend
        env:
          USER_FRONTEND: ${{ secrets.USER_FRONTEND }}
          HOST_FRONTEND: ${{ secrets.HOST_FRONTEND }}
        run: |
          ssh $USER_FRONTEND@$HOST_FRONTEND rm -r frontend/nonprod/*
          ssh $USER_FRONTEND@$HOST_FRONTEND tar xf frontend/beta.tar.gz -C frontend/nonprod/
