name: Frontend
on:
  push:
    branches:
      - master
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: self-hosted # runner label defined in repo settings
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Build frontend
        run: |
          cd web
          yarn
          yarn lint
          yarn types
          yarn prettier:check
          yarn build
          yarn test
        env:
          CI: true
