name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'yarn'
        cache-dependency-path: 'web/yarn.lock'
    - name: Build frontend
      run: |
        cd web
        yarn
        yarn build
        yarn test
      env:
        CI: true
