on: push
name: packtracker.io
jobs:
  build:
    name: Report to packtracker.io
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Report to packtracker.io
      uses: packtracker/report@2.2.8
      env:
        PT_PROJECT_ROOT: ./frontend
        PT_PROJECT_TOKEN: ${{ secrets.PT_PROJECT_TOKEN }}
